### ISSUE TITLE
AStarPathfinder should be fixed

### ISSUE THREAD

**Issue by SJ19** [apollo-rsps/apollo#106]
AStarPathfinder has a bug in it where this line 
https://github.com/apollo-rsps/apollo/blob/master/game/src/main/org/apollo/game/model/entity/path/AStarPathfindingAlgorithm.java#L76
call traversable without specifying the direction where the player is coming from. But even when adding a direction the paths don't really make sense. E.g. doesn't walk in a straight line from A to B where that would be the fastest way. Like this: https://i.gyazo.com/3a26aeade25393da908bd34b4e2f7b94.gif

**Comment by kylestev** [comment]
That's really weird. :+1:

**Comment by Major-** [comment]
Fixed in #191. Thanks for including the gif, that made it much easier to immediately see what was wrong.
