### ISSUE TITLE
Login issue after log out

### ISSUE THREAD

**Issue by Lmctruck30** [apollo-rsps/apollo#107]
Just downloaded a fresh copy and when you log in then log out you will get a stuck log in screen with no errors other then the client saying error connecting to server.

Mac running latest version of java 8.66. Client is a non edited MITB client.

**Comment by WizardJesse1** [comment]
I know this issue but I don't believe its the best way to fix

**Comment by WizardJesse1** [comment]
I have fixed it though

**Comment by lare96** [comment]
@WizardJesse1 share the fix

**Comment by WizardJesse1** [comment]
@lare96 i would love to share all my fixes if i knew how to setup github rofl

**Comment by lare96** [comment]
pastebin it if you have to

**Comment by WizardJesse1** [comment]
@lare96 I have been going to @garyttierney and telling him the bugs so i will give him the fixes if he wants to push them for me lolol

**Comment by WizardJesse1** [comment]
@Lmctruck30 http://recordit.co/QU9JhihGXD this?

**Comment by packersfan84** [comment]
epic nice

**Comment by ryleykimmel** [comment]
This is still an issue, @Major- am able to replicate it.

**Comment by Major-** [comment]
Rats

**Comment by Major-** [comment]
cc @garyttierney is this fixed in your local copy?

**Comment by garyttierney** [comment]
@Major- was never able to reproduce

**Comment by Major-** [comment]
cc @ryleykimmel please look into this as I haven't managed to reproduce it either

**Comment by ryleykimmel** [comment]
I can reproduce this every time. Log in, log out, try to log back in. Using master w/ no edits

**Comment by Rhys** [comment]
I am also able to reproduce this issue. Using master without any edits and running the 377 release.

**Comment by Artyom-M** [comment]
Hi, this also happens for me. Unedited, 377. Jesse's fix seems to work, though.
