### ISSUE TITLE
Npc Height issue

### ISSUE THREAD

**Issue by WizardJesse1** [apollo-rsps/apollo#109]
Pretty much if you go +1 height u see all the npcs from height 0

http://puu.sh/m3K2r/8a4905ab79.jpg

MORE:

When a player walks on height 1 it seems like it is setting the players height to 0 which is why this is happening

**Comment by garyttierney** [comment]
Steps to reproduce

http://webm.host/d1b8e/vid.webm

**Comment by WizardJesse1** [comment]
thx @garyttierney for posting a better reproduce

**Comment by garyttierney** [comment]
@WizardJesse1 please stop closing issues until they are officially fixed upstream

**Comment by Major-** [comment]
@WizardJesse1 what @garyttierney said - this makes it incredibly difficult to work out what is still an issue and what isn't.
