### ISSUE TITLE
Only npc/player speech dialogues can start conversations

### ISSUE THREAD

**Issue by WizardJesse1** [apollo-rsps/apollo#122]
Dialogues will not open unless the first dialogue is a npc_speech if it is any other type it will not work.

But if you have it continue to a player_speech or any other type it will be fine. It just has a problem starting

**Comment by WizardJesse1** [comment]
i tried to figure out more down of why it happens and if i do this it seems to fix it but I don't think this is how it should be fixed @Major- ??

http://0bin.net/paste/-FtnKOWGGWhithE5#A7E-owc/5ZnCt+WeHDhzQi3QHVNiTsW7mgyxGd6rRUW

**Comment by ryleykimmel** [comment]
@WizardJesse1 Unsure why it is written like that, certainly Npcs can open any kind of dialogue (not just speech!)

Ping @Major-

**Comment by Major-** [comment]
Yeah this is incorrect, I think we just want to get rid of the ` && dialogue.type == :player_speech || dialogue.type == :npc_speech` but I haven't taken a proper look, so that might be wrong.

This dialogue stuff really needs unit tests...

**Comment by Major-** [comment]
don't really know why i tagged this d-easy as getting this working properly is quite complicated... changing to d-medium

**Comment by cubeee** [comment]
http://webmup.com/052a2/vid.webm

Is this still happening or am I reproducing it wrong? @WizardJesse1 @Major-

**Comment by WizardJesse1** [comment]
@cubeee can u get players dialogue to work when u click the npc? instead of the command?

**Comment by cubeee** [comment]
http://webmup.com/2a998/vid.webm yep

**Comment by WizardJesse1** [comment]
@cubeee thanks cube, this can closed now since it clearly seems to be working fine
