### ISSUE TITLE
Replace maven with Gradle

### ISSUE THREAD

**Issue by Major-** [apollo-rsps/apollo#135]
Gradle offers much greater potential for customization, and better multi-language integration (which is going to be very useful when we actually have unit tests for ruby). 

Shouldn't be too tricky to port from maven to gradle.

**Comment by Major-** [comment]
Interested in doing this @garyttierney?

**Comment by Major-** [comment]
We want:

- [ ] Java test support (which is supported natively by gradle)
- [ ] Ruby test support (need to decide how to do this)
- [ ] Rubocop support

**Comment by garyttierney** [comment]
Closed in https://github.com/apollo-rsps/apollo/commit/d8f4aa88fe82c1725063a350d8be49e7abc0c12e.
