### ISSUE TITLE
Add functionality to Region which would allow for a synchronization optimization

### ISSUE THREAD

**Issue by ryleykimmel** [apollo-rsps/apollo#150]
Add functionality to the Region class which would allow us to optimize Apollo's synchronization to update surrounding regions of Players/Npcs rather than looping through their entire MobRepository.

Methods include:
- ```Set<Region> Region#getSurrounding``` - Gets the immediate surrounding regions that you can 'see' (define 'see' as standing in the middle of a region how many other regions can you see in your viewport)
- ```<T extends Entity> Set<T> Region#getEntities(EntityType... types)``` - Gets all of the Entities within an entire Region, not just on a single position

**Comment by Major-** [comment]
Second one should either return `Stream<Entity>` or we shouldn't implement it at all, otherwise we'll be iterating over the entities twice (once for filter, once for encoding)

**Comment by ryleykimmel** [comment]
```java
entities.keySet().stream().map(position -> getEntities(position, types)).collect(Collectors.toSet());
```

**Comment by ryleykimmel** [comment]
How would you return ```Stream<Entity>``` when ```entities.values` returns a Collection<Set<Entity>>? I don't think we can map to a single set without iterating twice.

**Comment by Major-** [comment]
[flatMap()](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#flatMap-java.util.function.Function-) should work for that

**Comment by ryleykimmel** [comment]
Yeah, feeling stupid right now. Totally forgot that was a thing.

```java
  @SuppressWarnings("unchecked")
  public <T extends Entity> Stream<T> getEntities(EntityType... types) {
    Set<EntityType> set = ImmutableSet.copyOf(types);
    return (Stream<T>) entities.values().stream().flatMap(Collection::stream).filter(entity -> set.contains(entity.getType()));
  }``` so something like this could suffice
