### ISSUE TITLE
Generate message codecs at runtime

### ISSUE THREAD

**Issue by Major-** [apollo-rsps/apollo#161]
There is a huge amount of boilerplate code used to encode/decode messages. This should be done using some sort of DSL.

**Comment by Major-** [comment]
Current syntax (which may change) looks like:

```rust
downstream magic_on_player {
    opcode: 249
 
    data { 
        index: u16,
        spell: little u16,
    }
}
```

**Comment by garyttierney** [comment]
update on this? @Major-

**Comment by Major-** [comment]
Parser is done but slightly hacky, code generation doesn't exist. Will push to a branch later today (10th), probably

**Comment by Buroa** [comment]
Are you talking about: https://github.com/Buroa/Eryna/tree/master/data/plugins/_decoders, https://github.com/Buroa/Eryna/tree/master/data/plugins/_encoders

**Comment by Major-** [comment]
No, that's just defining them in ruby. You can see the branch that has some of this work in [here](https://github.com/apollo-rsps/apollo/tree/codec_gen).

**Comment by Major-** [comment]
Not worth the effort, may revisit in future
