### ISSUE TITLE
Wilderness Logout/Login Check

### ISSUE THREAD

**Issue by WizardJesse1** [apollo-rsps/apollo#164]
Produced - http://recordit.co/mlPOGQksq0

We need to check if the player is in the wilderness on login

**Comment by WizardJesse1** [comment]
Ya i see where it happen which i did fix easy. but now in order to send it on you need walk 1 tile?

**Comment by Major-** [comment]
What code did you use to fix it?

**Comment by WizardJesse1** [comment]
It just didn't send the interface so I resent the overlay on login

**Comment by WizardJesse1** [comment]
Where the Check is

**Comment by ryleykimmel** [comment]
That's not a good fix -- area listeners should be notified upon login instead.

**Comment by WizardJesse1** [comment]
o alright @ryleykimmel

**Comment by ryleykimmel** [comment]
Yeah this is a flaw with the way the MobPositionUpdateEvent is sent.

```java
public final void setPosition(Position position) {
		if (!position.equals(this.position) && world.submit(new MobPositionUpdateEvent(this, position))) {
```

The event is only sent for Mobs (intentional? all entities should be able to set their position IMO) and it's only sent when ```setPosition(Position)``` is called, when you login your position is set via the Mob constructor and not from the ```setPosition(Position)``` method.
