### ISSUE TITLE
Teleporting into the wilderness

### ISSUE THREAD

**Issue by WizardJesse1** [apollo-rsps/apollo#169]
Produced - http://recordit.co/PmeakKHykb

The biggest issue I can see where this problem can be known the most

* Mage bank teleport from safe to wilderness

**Comment by Major-** [comment]
That's interesting...

I think there's a clientscript we can use for the wilderness level anyway, but the fact that this is showing '-4' means the wilderness level is being calculated before the player's position has been updated.
