### ISSUE TITLE
Location plugins use the wrong NPCs in some cases

### ISSUE THREAD

**Issue by Major-** [apollo-rsps/apollo#174]
Some of the location plugins spawn the wrong NPCs, e.g. Al Kharid's bankers and shop assistants are probably wrong, and Edgeville's bankers are probably wrong too.

Someone just needs to log in to OSRS (or find a YouTube video from the appropriate time) and work out what the bankers look like, then replace the current ids with the correct ids (which should be easy to find, using `::lookup npc npc_name_here`).

- [x] Edgeville bankers
- [x] Al Kharid bankers
- [x] Al Kharid general store staff

**Comment by Major-** [comment]
@WizardJesse1 did both of the Al Kharid ones (thanks!) so we only have Edgeville left

**Comment by WizardJesse1** [comment]
@Major- Edgeville is done now too

**Comment by Major-** [comment]
Great, thanks
