### ISSUE TITLE
HintIconMessage is only functional for players/npcs

### ISSUE THREAD

**Issue by Major-** [apollo-rsps/apollo#179]
There are several types of entities that can have [hint icons](https://github.com/apollo-rsps/apollo/blob/e4778105f5036636bb0bfa2493267588c1045b93/game/src/main/org/apollo/game/message/impl/HintIconMessage.java), but currently we only have it implemented for players and npcs. There are at least 2 or 3 different types for objects (which I think are dependent on object size, but can't quite remember), and we need all of these implemented.

This is blocking the tutorial plugin, so its pretty important.

**Comment by Major-** [comment]
Think @ryleykimmel is working on this

**Comment by ryleykimmel** [comment]
Self assigned, will be making a PR soon.
