### ISSUE TITLE
Replace mined rocks with their empty equivalents

### ISSUE THREAD

**Issue by Major-** [apollo-rsps/apollo#182]
Currently the mining plugin does not replace rocks that have had ore mined from them, meaning you can endlessly mine from the same rock with no time limits.

This will also require some sort of Task to replace expired rocks with their ore-containing equivalents, after the appropriate period of time has elapsed.

**Comment by tlf30** [comment]
I think this can be closed now as it is fixed and merged into the new kotlin plugin system.

**Comment by Major-** [comment]
Fixed in e61f4ef.
