### ISSUE TITLE
Don't guarantee a player will always successfully mine ore

### ISSUE THREAD

**Issue by Major-** [apollo-rsps/apollo#183]
Currently the [mining plugin](https://github.com/apollo-rsps/apollo/blob/master/data/plugins/skill/mining/mining.rb#L65) always guarantees a player will successfully mine a rock, whereas in RS this usually takes several ticks at minimum (and typically much longer for higher level rocks such as rune). We need some sort of probability function.

**Comment by tlf30** [comment]
Fixed in Kotlin port of plugin

**Comment by tlf30** [comment]
I think this can be closed now as it is fixed and merged into the new kotlin plugin system.

**Comment by Major-** [comment]
@tlf30 Great, thanks a lot!
