### ISSUE TITLE
Ring enchantment animation is probably wrong

### ISSUE THREAD

**Issue by Major-** [apollo-rsps/apollo#185]
The animation [currently used](https://github.com/apollo-rsps/apollo/blob/master/data/plugins/skill/magic/enchant.rb#L11) for enchanting rings is the high-level alchemy animation, which seems unlikely to be accurate. We just need to find the correct animation id and replace the current id with it.

**Comment by WizardJesse1** [comment]
Fixed

**Comment by Major-** [comment]
Fixed in 67c2fd2.
