### ISSUE TITLE
Chance of receiving higher-tier fish from spots is wrong

### ISSUE THREAD

**Issue by Major-** [apollo-rsps/apollo#187]
Currently the Fishing plugin [randomly selects a possible fish](https://github.com/apollo-rsps/apollo/blob/master/data/plugins/skill/fishing/fishing.rb#L68) when fishing from spots that can produce multiple fish. In RS this is not weighted evenly (trout/salmon are weighted 70/30, and tuna/swordfish is probably about the same).

**Comment by WizardJesse1** [comment]
@Major- do u have a way to prove that its like this ;o? i always though it was based on the better level u were the better chance of getting a higher fish

**Comment by Major-** [comment]
A few years back I trained from ~50 to 90 on salmon/trout and the ratio stayed the same the entire time, so pretty confident it's not level-dependent

**Comment by WizardJesse1** [comment]
alright ill do this when i get to fishing

**Comment by tlf30** [comment]
This is fixed in the kotlin fishing plugin.
