### ISSUE TITLE
Equipment Disappearing 

### ISSUE THREAD

**Issue by WizardJesse1** [apollo-rsps/apollo#221]
How to produce

http://recordit.co/Nc07i8DLKs

**Comment by cubeee** [comment]
Line that causes this: https://github.com/apollo-rsps/apollo/blob/ba1537a9e42360eb28eb7c3eb5588f81be833f8c/game/src/main/org/apollo/game/message/handler/EquipItemHandler.java#L133
Changing remove to removeSlot seemed to work which means the bug exists in Inventory#remove(id, amount)?
