### ISSUE TITLE
Shop Out of stock issue

### ISSUE THREAD

**Issue by WizardJesse1** [apollo-rsps/apollo#235]
If a shop sells the item from its stock (*not* because it bought it from a player) then the amount needs to be set to 0 rather than removing the item.

**Comment by WizardJesse1** [comment]
I'm currently working upon fixing this.

**Comment by WizardJesse1** [comment]
Looking more deeper into this bug it seems like it happens if you set the buy type to all since once I removed it the issue was fixed. @Major- @ryleykimmel  any thoughts?

**Comment by WizardJesse1** [comment]
caused by  keep = invent_item.amount == buy_amount && shop.buys == :own

if you add all in it does fix the issue but makes problems when selling an items to an all shop

**Comment by WizardJesse1** [comment]
@ryleykimmel any ideas?

**Comment by ryleykimmel** [comment]
Don't allow stock items to be bought out, set their amount to 0 rather than removing them from the store (this is how RS does it)

**Comment by WizardJesse1** [comment]
@ryleykimmel yes and thats what it is doing but what about items like whip etc in a general store that do need removed?

**Comment by ryleykimmel** [comment]
Only set _stock items_ to 0, ones that do not get restocked are ok to be removed like usual.

**Comment by WizardJesse1** [comment]
@ryleykimmel yes but for shop type buys :all the items will get removed even if its set stock

**Comment by WizardJesse1** [comment]
thats the bug

**Comment by Major-** [comment]
@WizardJesse1 any idea what this bug was/is?

**Comment by Major-** [comment]
Fixed in #348.
