### ISSUE TITLE
Pickaxe Searching Mining

### ISSUE THREAD

**Issue by WizardJesse1** [apollo-rsps/apollo#247]
doge

**Comment by Major-** [comment]
When you close an issue please give a reason (e.g. "fixed in [commit]")

**Comment by Major-** [comment]
@WizardJesse1 is this still an issue? i don't know what the original problem was

**Comment by WizardJesse1** [comment]
@Major- it would be fixed in my mining if it was

**Comment by tlf30** [comment]
@WizardJesse1 What was the original issue?
 I am currently working on the kotlin version of the plugin for mining and would like to know if there is a bug in the original ruby that might be pulled over into the kotlin version.

**Comment by Major-** [comment]
Issue was that you wouldn't use the best pickaxe you had, it would use whatever it found first

**Comment by tlf30** [comment]
Oh OK. That is fixed in the kotlin version I wrote.

**Comment by tlf30** [comment]
I think this can be closed now as it is fixed and merged into the new kotlin plugin system.

**Comment by Major-** [comment]
@tlf30 Excellent, thanks!
