### ISSUE TITLE
Explanation on Archive class decode method

### ISSUE THREAD

**Issue by KGALLET** [apollo-rsps/apollo#250]
Hello,  
I need some explanations on the `public static Archive decode(ByteBuffer buffer)` method in the `src/main/org.apollo.cache/archive/Archive.java` class. In this part of the code :

```
	public static Archive decode(ByteBuffer buffer) throws IOException {
		int extractedSize = BufferUtil.readUnsignedMedium(buffer);
		int size = BufferUtil.readUnsignedMedium(buffer);
		boolean extracted = false;

		if (size != extractedSize) {
			byte[] compressed = new byte[size];
			byte[] decompressed = new byte[extractedSize];
			buffer.get(compressed);
			CompressionUtil.debzip2(compressed, decompressed);
			buffer = ByteBuffer.wrap(decompressed);
			extracted = true;
		}
    ...
    ...
    }
```
		
I don't get why you have to check `if (size != extractedSize)` because you call the same method `readUnsignedMedium` on the same buffer. Firstly, we thought that the buffer will be modified after the initialization of the extractedSize variable, but if not, there is no difference.

Can someone explain us why there is this condition here?

Thanks

**Comment by ryleykimmel** [comment]
The buffer is modified, you are correct.

**Comment by Major-** [comment]
Ryley is correct. Also, check out our irc channel, which is a better place to ask questions like this.
