### ISSUE TITLE
Create a CONTRIBUTING.md 

### ISSUE THREAD

**Issue by CharlesVaneenoo** [apollo-rsps/apollo#255]
Hello,
We have think that could be helpfull to create a CONTRIBUTING.md for future contributors.
It will explain how they can test their code, ask for help (IRC chat, mail... ), rules ...
It can contain for example a template for future PR and this can bring a better understanding between contributors. 
Let we know what you think about that !
Thanks.

**Comment by Major-** [comment]
Great idea

**Comment by Major-** [comment]
cc @ryleykimmel @garyttierney 

Maybe this should be done after the gradle update

**Comment by cubeee** [comment]
+1

**Comment by garyttierney** [comment]
+1

**Comment by ryleykimmel** [comment]
+1

**Comment by CharlesVaneenoo** [comment]
CONTRIBUTING.md was created, i close my issue.
Thank you for your help.
