### ISSUE TITLE
Ruby REPL for in-game debugging

### ISSUE THREAD

**Issue by garyttierney** [apollo-rsps/apollo#261]
This is something which I think could be invaluable for testing. Currently testing can only be done in-game through commands sent from the client to the server, which then invoke some functions. That isn't really ideal if I want to quickly test that my new functionality works with the client properly.

Once we have a better build setup we can probably leverage some rubygem for this, dropping the difficulty down from hard to maybe medium. As of now we don't have any way to do integration testing with the client and I think this is a good start.

**Comment by garyttierney** [comment]
Another view on this issue could be: get ruby debuggers working with embedded jruby

**Comment by Major-** [comment]
Closing as part of the resolution of #310.
