### ISSUE TITLE
Client not working on OS X 

### ISSUE THREAD

**Issue by KGALLET** [apollo-rsps/apollo#265]
Hello, 

As we saw with @cubeee and sfix (@garyttierney ?) on IRC, we would like to let you know that the client is not working on OS X.
Here are my specifications : 
`MacBook Air (13" Mid 2013)`
`OS X El Capitan 10.11.3`
`Intel Core i7`
`8 Go DDR3`
`Intel HD Graphics 5000`

What we saw when the server is on, and we start the client is :
![client](https://cloud.githubusercontent.com/assets/14168629/13531349/5813f770-e226-11e5-855d-f8f69c445287.png)

Apparently, I googled about same issue and some users are saying that it could be better to run it with jre6.

Thank's

**Comment by garyttierney** [comment]
Leaving open, as it might be good to add to a future wiki page.

**Comment by Lmctruck30** [comment]
THIS ISSUE CAN BE CLOSED. TESTED WITH JAVA 1.8.112 ISSUE IS FIXED NOW.

**Comment by Lmctruck30** [comment]
YOU NEED TO COMPILE THE CLIENT WITH JDK 8.112 THEN RUN ALSO ON 8.112 FIXED THE DEDICATED GPU ON APPLE COMPUTERS

**Comment by Lmctruck30** [comment]
@garyttierney @ryleykimmel This issue is resolved. Please close. Here is the OpenJDK ticket about the issue. https://bugs.openjdk.java.net/browse/JDK-8041900

**Comment by KGALLET** [comment]
Closed
