### ISSUE TITLE
equipment-317.dat needs updating

### ISSUE THREAD

**Issue by nstroupr** [apollo-rsps/apollo#266]
equipment-317.dat needs updating to reflect the recent changes that were made to EquipmentDefinitionParser.

**Comment by Major-** [comment]
Tbh we probably don't want to distribute these files in the git repo anyway

**Comment by nstroupr** [comment]
So then remove it all together and parse equipment definitions from the cache? Also, if you change the revision to 317, you get a lot of Ruby Plugin errors due to trying to spawn an NPC from the 377 revision. So the spawn files need the appropriate revision switches.

**Comment by WizardJesse1** [comment]
@nstroupr its because i added npcs that were in 377 when i did npc spawns. if you want to stay on 317 just simply remove the npcs that there messing up on or you could use a 377 cache working on a 317 deob.

**Comment by garyttierney** [comment]
With regards to plugin issues: Apollo no longer officially targets 317, so anything other than 377 will require a bit of work.

Since updating these data files isn't really a change which should be committed to the repository, I'm closing this and creating a new issue to get rid of them.
