### ISSUE TITLE
Duplicate interface

### ISSUE THREAD

**Issue by CharlesVaneenoo** [apollo-rsps/apollo#283]
Hello, 
I found 2 similar interfaces named `ClosedInterfaceMessage` and `CloseInterfaceMessage` in the package `org.apollo.game.message.impl`.
What do you think about removing one of these interfaces ?
Thanks.

**Comment by ryleykimmel** [comment]
They are both different Messages entirely.

CloseInterfaceMessage is an upstream message which requests that the client closes all open interfaces.

ClosedInterfaceMessage is a downstream message which notifies the server that an interface has been closed.

**Comment by CharlesVaneenoo** [comment]
Thanks for you answer.
