### ISSUE TITLE
Support for Mob following

### ISSUE THREAD

**Issue by garyttierney** [apollo-rsps/apollo#287]
Self explanatory, we need support for following. The code itself can be written as is but will need #222 to work correctly.

This currently blocks #260.

**Comment by garyttierney** [comment]
I have a lot of code to work on here at the moment so any takers for this? cc @ryleykimmel @Major- @WizardJesse1

**Comment by Major-** [comment]
Going to need to spend some time thinking about this as the actual interaction is quite tricky (e.g. to imitate RS' weird dancing)

**Comment by WizardJesse1** [comment]
@Major- doesn't it just the follower just follow the leaders last tile? which would cause that

**Comment by cubeee** [comment]
@Major- Players constantly try to get behind the other when following which causes the dancing effect

**Comment by garyttierney** [comment]
Note: following can't be an `Action`, since it's used by other plugins (you can follow and attack)

**Comment by ryleykimmel** [comment]
@Major- Following the players last direction produces the 'dancing' effect.

**Comment by WizardJesse1** [comment]
anything new on this @garyttierney since I though it was done?

**Comment by garyttierney** [comment]
@WizardJesse1 AFAIK it is. CC @stevesoltys

**Comment by garyttierney** [comment]
Closed in https://github.com/apollo-rsps/apollo/commit/e5a6638e2fc0bc4f524906639c42893998c4e594.
