### ISSUE TITLE
other players facing south when first logging in

### ISSUE THREAD

**Issue by Lmctruck30** [apollo-rsps/apollo#305]
Simple fix, players are facing south on the client that just logs in for the first time:

Client 1: player logged in and is facing north
Client 2: player logged in and now on client 2 screen shows client 1 facing south but on client 1 screen client 1 is facing north.

**Comment by ryleykimmel** [comment]
This is how it works on RuneScape, I'm pretty sure..

**Comment by WizardJesse1** [comment]
@ryleykimmel it shouldn't be like that

**Comment by ryleykimmel** [comment]
Pretty sure it is, man.

https://twitter.com/runescape/status/532322387228753920

**Comment by hyperkilljoy** [comment]
Client 1 = bob
Client 2 = tom
bob logs in and moved to face north
tom logs in faced south (default)
tom looks at bob who is faced south on his screen
bob is faced north and tom is faced south on his screen.

Is that right? Sounds like when a new client logged in, everyone who is logged in is faced south for that new client even though on their client, they are not.

**Comment by Lmctruck30** [comment]
@ryleykimmel @WizardJesse1 

Issue is not you logging in facing south. You see other players that are facing another direction facing south not in accordance to what that player sees on their client.

**Comment by ryleykimmel** [comment]
Right, everyone faces south when you log in, including yourself.

Just logged into RS all facing south by default: http://i.imgur.com/Deq8lap.png

**Comment by Lmctruck30** [comment]
Dammit @ryleykimmel you always have to be right lol

**Comment by Lmctruck30** [comment]
Not an issue.
