### ISSUE TITLE
Collision: unable to walk to tile in bounds of object

### ISSUE THREAD

**Issue by garyttierney** [apollo-rsps/apollo#313]
Reported by a user on IRC:

```
9:28 < WizardJesse> u cant walk to certain objs that you should be able to walk next to
19:28 < WizardJesse> uhh
19:29 < sfix> hmm thats strange
19:29 < sfix> i did a diff between the clipping map generated by the client and the clipping map generated by the server
19:29 < sfix> is it a dynamic object by any chance (i.e., not part of the static maps)?
19:29 < WizardJesse> 3099, 3360
19:29 < WizardJesse> i couldnt walk next to the chair
19:29 < WizardJesse> but u should be able to
19:30 < sfix> is that the position of the chair or your position?
19:30 < sfix> just logging it in an issue so i dont lose track of it
19:30 < WizardJesse> the position the player cant walk to
19:31 < sfix> o ok so the tile adjacent to the chair
19:31 < WizardJesse> it mite be because of the chairs rotation
19:31 < sfix> its not just a 1x1 chair then?
19:31 < WizardJesse> http://i.imgur.com/fK3DFLv.png
```

**Comment by garyttierney** [comment]
Works fine in master.  @WizardJesse1 any further info?

**Comment by WizardJesse1** [comment]
@garyttierney we agreed that it was maybe the way I was obtaining the src which was from downloading it as a zip. I never got to test the other way to test but I believe it should be fine.

**Comment by garyttierney** [comment]
@WizardJesse1 I'll keep this open for now in case anything new crops up.

If you want to upload the source zip you got we can have a look at that (and report as an issue to GitHub).

**Comment by WizardJesse1** [comment]
@garyttierney https://github.com/apollo-rsps/apollo/archive/master.zip is the link i'm using when I tested

**Comment by Lmctruck30** [comment]
@garyttierney Unable to replicate this issue.

**Comment by WizardJesse1** [comment]
@garyttierney we realized this was an issue from downloading the source from git
