### ISSUE TITLE
Bug: Mining pauses and gives infinite ores

### ISSUE THREAD

**Issue by rlgenesis** [apollo-rsps/apollo#315]
Tested this in mining guild with tin ores. Clicked it and after a few second character pauses and gets infinite ores and the ore never depletes.

**Comment by rlgenesis** [comment]
Fix: Line 68 mining.rb

Change to: 

name = name_of(:object, @ore.id).sub(/ ore$/, '').downcase

**Comment by WizardJesse1** [comment]
I don't believe mining ore ever had depleting unless you put mine in that i still need to push lol

**Comment by rlgenesis** [comment]
Mind pushing the update @WizardJesse1?

**Comment by WizardJesse1** [comment]
ya ill get to it @rlgenesis I just didn't want to finish what had to be changed due to hearing about the language changing

**Comment by rlgenesis** [comment]
@WizardJesse1 Ah okay thank you, yeah I don't agree with the change in the plugin system either. Ruby is actually why I decided to pick up Apollo lol.

**Comment by Major-** [comment]
@WizardJesse1 fwiw stuff like this would be really trivial to convert to [language] if we do change, please don't be put-off from contributing stuff in ruby by that possibility

**Comment by garyttierney** [comment]
On top of what @Major- said, any conversion will be done in a sweeping change (likely by me or whoever is involved in getting it done).  We won't be mix and matching JRuby and <X> language plugins for a while.

**Comment by tlf30** [comment]
I have ore depletion working in my current port of the plugin. See #346

**Comment by tlf30** [comment]
I think this can be closed now as it is fixed and merged into the new kotlin plugin system.

**Comment by Major-** [comment]
Fixed in e61f4ef.
