### ISSUE TITLE
No current way to replace objects

### ISSUE THREAD

**Issue by rlgenesis** [apollo-rsps/apollo#351]
At the moment there is no current way to replace objects. 

There's region.removeEntity, and region.addEntity, but no replacing. Since this is code that is recycled/re-used in a lot of instances (such as skilling, picking objects, etc) I would imagine it would have to be added in the core.

**Comment by garyttierney** [comment]
:+1:

Atomically replacing objects in core instead of plugins is a good idea, I think.

**Comment by tlf30** [comment]
I agree that this would be a great feature.

**Comment by tlf30** [comment]
I have noticed in the plugins I am working on, that when removing then adding an object, certain objects in the game world disappear instead. So a working way to replace objects consistently is in need.

**Comment by gruckion** [comment]
Is it possible to replace any object type specified at s specific location? For example wall lamp and wall are different object types.

I am also aware that farming patch manipulation is carried out using the config function that is similar to how one manipulates the state of toggle buttons on interfaces (e.g. the options interface).

Hence you can change an object, such as farming patch, through this type of manipulation. However my experience of 377 is low and I am unsure of what packet I'd is used. I will check later, chase me up if I forget and this is needed.

**Comment by gruckion** [comment]
@tlf30 this is for to the object type

**Comment by Major-** [comment]
Note that farming patches aren't replacing objects, they're client-local state changes (config stuff, as you said), and so they're explicitly out of scope of this issue, which is concerned only with replacing objects using the frames for that. As for the specific types (wall lamp etc) we have some documented [here](https://github.com/apollo-rsps/apollo/blob/master/game/src/main/org/apollo/game/model/entity/obj/ObjectType.java#L10) that I think are correct (the list that people post occasionally, originally written by maxi, is mostly inaccurate). Identifying the remaining types would be nice although not that important.

**Comment by tlf30** [comment]
@gruckion, I am not sure now that the new changes are in place, that was the old way I was trying to do it, but it was inconsistent. But now there is a new way of doing this. 
In the mining plugin, the was it was done using the new system was
https://github.com/apollo-rsps/apollo/blob/1c8bc3a009661665f932a1b239983803c7ad3ac0/game/plugin/skills/mining/src/mining.plugin.kts#L102

Which got the object via:
https://github.com/apollo-rsps/apollo/blob/1c8bc3a009661665f932a1b239983803c7ad3ac0/game/plugin/skills/mining/src/mining.plugin.kts#L21-L25

So, it is by position, and type. I do not see any reason that you could not replace other types of object the same way. This is also how the woodcutting plugin works.

**Comment by Major-** [comment]
Fixed in a54485e.
