### ISSUE TITLE
Missing Classfile for Ruby Combat Branch

### ISSUE THREAD

**Issue by Faris-Mckay** [apollo-rsps/apollo#380]
Did `java_import 'org.apollo.game.model.entity.AnimationSet'` ever exist ? Have looked through past commits on that branch, seemed to be used by the plugin but was never added to the project. Possibly gitignored?

@garyttierney hopefully could have some more insight on this. I'm aware that the Ruby plugins are being ported to Kotlin by the way

Trace:  
`NameError: cannot load Java class org.apollo.game.model.entity.AnimationSet
              for_name at org/jruby/javasupport/JavaClass.java:204
       get_proxy_class at org/jruby/javasupport/JavaUtilities.java:34
  block in java_import at uri:classloader:/jruby/java/core_ext/object.rb:47
                   map at org/jruby/RubyArray.java:2300
           java_import at uri:classloader:/jruby/java/core_ext/object.rb:34
                 <top> at C:\Users\FarisMcKay\Documents\GitHub\apollo\.\data\plugins\combat\weapon.rb:5
org.jruby.embed.EvalFailedException: (NameError) cannot load Java class org.apollo.game.model.entity.AnimationSet`

**Comment by garyttierney** [comment]
It was renamed to AnimationMap in this tree: https://github.com/apollo-rsps/apollo/blob/0e98d604f140866ed2557b9fdd90634b7e544cdc/game/src/main/java/org/apollo/game/model/entity/AnimationMap.java but never existed upstream

**Comment by garyttierney** [comment]
As that branch isn't supported, I'm closing this.  If you intend on using that code I'd advise getting a copy of it now.  It'll likely be removed from upstream when all of the functionality exists in Kotlin.
