### ISSUE TITLE
Port the Ruby Herblore plugin to Kotlin

### ISSUE THREAD

**Issue by garyttierney** [apollo-rsps/apollo#385]
Tracker for converting the Herblore skill to Kotlin (#338)

**Comment by garyttierney** [comment]
~Blocked on #381~ actually these are unrelated

**Comment by Major-** [comment]
#189 needs an answer
Edit: for now keep the dialogues as-is.

**Comment by Major-** [comment]
Fixed in 68b7891 (actual commit a528379).
