### ISSUE TITLE
Command to get another player's position

### ISSUE THREAD

**Issue by Major-** [apollo-rsps/apollo#409]
Expand the existing `::pos` command to support `::pos [player]`, which displays the position of the specified player.

- Should require moderator rights to use.
- Should display something like "Player [playername] is not currently online." if the specified player is not logged in.

Mentoring from the project maintainers is available for anyone who wishes to work on this issue - please join our Slack team (link in the main project README) and let us know.

**Comment by Arham4** [comment]
I assume this is an issue for beginners (from the mentoring label)?

**Comment by Major-** [comment]
Yes, absolutely, maybe we can make the labels clearer. Slack is probably the best way to ask for assistance, in #plugin-help.
