### ISSUE TITLE
Fix message releasing (netty 4)

### ISSUE THREAD

**Issue by dosier** [apollo-rsps/apollo#419]
`ReferenceCountUtil.release(message)`

Documentation of the release method states:
     * If the specified message doesn't implement {@link ReferenceCounted}, this method does nothing.

The messages don't implement "ReferenceCounted" resulting in nothing being released.

**Comment by dosier** [comment]
Leak report as requested by @ryleykimmel (this is PARANOID level)

Full report: https://pastebin.com/DqwF8rbV

Preview:
Nov 11, 2018 12:41:36 AM io.netty.util.ResourceLeakDetector reportTracedLeak
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 4
#4:
	io.netty.buffer.AdvancedLeakAwareByteBuf.readByte(AdvancedLeakAwareByteBuf.java:396)
	org.empyrean.net.GamePacketReader.get(GamePacketReader.java:88)
	org.empyrean.net.GamePacketReader.getUnsigned(GamePacketReader.java:363)
	org.empyrean.net.GamePacketReader.getUnsigned(GamePacketReader.java:336)
	org.empyrean.net.release.r317.codec.in.PlayerDesignMessageDecoder.decode(PlayerDesignMessageDecoder.java:31)
	org.empyrean.net.release.r317.codec.in.PlayerDesignMessageDecoder.decode(PlayerDesignMessageDecoder.java:16)
	org.empyrean.net.codec.GameMessageDecoder.decode(GameMessageDecoder.java:41)
	org.empyrean.net.codec.GameMessageDecoder.decode(GameMessageDecoder.java:18)
	io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	java.base/java.lang.Thread.run(Thread.java:844)

**Comment by dosier** [comment]
Extending GamePacket with DefaultByteBufHolder and using the inherited content() method instead of accessing payLoad directly could potentially fix this (DefaultByteBufHolder implements ReferenceCount). Will try this out tomorrow and see whether it fixes the issue.

**Comment by rmcmk** [comment]
Tested this fix on a `SIMPLE` and `PARANOID` level last night. Didn't mean to steal your thunder but I had already written the code. See #420

**Comment by dosier** [comment]
> Tested this fix on a `SIMPLE` and `PARANOID` level last night. Didn't mean to steal your thunder but I had already written the code. See #420

Looks good. I also received these messages for login requests. Which I fixed by adding 
`payload.release();`
Under 
`payload.readBytes(rsaBytes);`
However, I am not sure whether this is sufficient in the case of login requests being invalid and thus not reaching the payload decoding in the LoginDecoder.

**Comment by rmcmk** [comment]
We should only need to release buffers we create. If I remember correctly, we do create one buffer in the login block for RSA. That likely needs released whenever we're done with it.

**Comment by dosier** [comment]
I am not familiar with netty 3.x but since 4 ByteBuf is always reference counted and because of the new changes (for the sake of improving performance), the GC no longer cleans up ByteBuf objects automatically. It states in the docs that you always have to release the ByteBuf manually in the pipeline's upstream handler that last accessed it. But once again I am not sure how to best deal with the login requests that don't make it to the payload decoding, the current design of the login protocol would make for a rather inelegant solution.

**Comment by Major-** [comment]
Closing due to #420. If the RSA buffer is being leaked that seems like a separate issue.
