### ISSUE TITLE
Slack link not working

### ISSUE THREAD

**Issue by dosier** [apollo-rsps/apollo#446]
"This invite link is no longer active.
Please check with the person who shared it with you to see if there's a new link available."

**Comment by Major-** [comment]
Thanks, I've updated it. [This should work too](https://join.slack.com/t/apollo-rsps/shared_invite/enQtMjQ0NTYwNzkwMjExLTdlZDJjZTUxODA5NDdjYTQ1ZGM0YjgwN2I3ZjlkZmVmMGIwZTA3Y2M3ZDI5NTk3N2ZjN2VmNzYwZDk4NmE4ZjE).
