### ISSUE TITLE
Improve existing skills that suffer from outdated or poor code.

### ISSUE THREAD

**Issue by Major-** [apollo-rsps/apollo#50]
Many of the ruby plugins, particularly some of the skills, suffer from poor/outdated code that needs to be improved.

**Comment by ryleykimmel** [comment]
@Major- What code specifically is this related to _now_?

**Comment by Major-** [comment]
@ryleykimmel probably most of them... lots of the ruby code is bad.

**Comment by ryleykimmel** [comment]
@Major- Figured some of it was touched up on when this was in the private repo since this issue is from January

**Comment by Major-** [comment]
Closing in favour of more specific issues.
