### ISSUE TITLE
Possible player updating issue

### ISSUE THREAD

**Issue by Lmctruck30** [apollo-rsps/apollo#56]
This is a copy of the most recent version of apollo and found this issue happen when messing around making trading. This has happened a few times and this is one of the times I have been able to get a screen shot of it happening

http://prntscr.com/6h348a

**Comment by atomicint** [comment]
Any other information on how this happened?

**Comment by Lmctruck30** [comment]
I wish. I have both my clients spitting movement updates and they match.

**Comment by Major-** [comment]
Could be related to an intermittent walking bug we have been experiencing (and possibly fixed in the private fork). I'll leave this open for a while in case it happens to you again.

**Comment by Lmctruck30** [comment]
Sounds Good.
