### ISSUE TITLE
Private message issue not sending

### ISSUE THREAD

**Issue by Lmctruck30** [apollo-rsps/apollo#57]
Issue in the plugin where message.compressed_message should be changed to message.compressed_chat

------ This will fix it

require 'java'

java_import 'org.apollo.game.message.impl.ForwardPrivateChatMessage'
java_import 'org.apollo.game.model.World'
java_import 'org.apollo.game.model.setting.PrivacyState'

on :message, :private_chat do |ctx, player, message|
  friend = $world.get_player(message.username)
  friend.send(ForwardPrivateChatMessage.new(player.username, player.privilege_level, message.compressed_chat)) if interaction_permitted(player, friend)
end

# Checks if the sender is permitted to interact with the friend they have added:
def interaction_permitted(sender, friend)
  if friend == nil || friend.has_ignored(sender.username)
    return false
  end
  
  return friend.friends_with(sender.username) ? friend.friend_privacy != PrivacyState::OFF : friend.friend_privacy == PrivacyState::ON
end

**Comment by atomicint** [comment]
Fixed, thanks. @Major-  or @Lmctruck30 close since I do not have the permissions to do so.

**Comment by Major-** [comment]
Thanks for all the reports Lmctruck!
