### ISSUE TITLE
Issue with ItemDefinitionDecoder

### ISSUE THREAD

**Issue by Lmctruck30** [apollo-rsps/apollo#58]
Currently it look like this
"} else if (opcode == 78 || opcode == 79 || opcode >= 90 || opcode <= 93 || opcode == 95) {"

Needs to be 

"} else if (opcode == 78 || opcode == 79 || opcode == 90|| opcode == 91|| opcode == 92 || opcode == 93 || opcode == 95) {"

or

"} else if (opcode == 78 || opcode == 79 || (opcode >= 90 && opcode <= 93) || opcode == 95) {"

**Comment by atomicint** [comment]
Fixed awhile ago actually, @Major-  close please.
