### ISSUE TITLE
BankMessageHandler Withdraw Entered Amount not working

### ISSUE THREAD

**Issue by Lmctruck30** [apollo-rsps/apollo#59]
Issue in method "withdraw"
"EnterAmountListener listener = new BankDepositEnterAmountListener(player, message.getSlot(), message.getId());"

Change to 
"EnterAmountListener listener = new BankWithdrawEnterAmountListener(player, message.getSlot(), message.getId());"

Issue using the wrong listener.

**Comment by atomicint** [comment]
Fixed.
