### ISSUE TITLE
Consideration for Packet Normalization

### ISSUE THREAD

**Issue by Hadyn** [apollo-rsps/apollo#62]
I think one of the clunkier feelings to Apollo when developing for it is the fact that each packet has a one to one class representation of a message (sometimes its one to many since an option field can be attributed say option packets), a one to one class representation of a message to an encoder/decoder, and a one to one class representation of a handler. When it comes down to brass tacks it feels very clunky and in my opinion is one of the greatest design flops with the source.

I'm proposing that with the found knowledge of the real packet ids which is represented in the PacketConstant class in the older Runetek engine that in the session pipeline that all packets be normalized before decoding to cut down on some of this class overhead. The strategy for this would be to rearrange the bytes in logical and homogeneous order of similarly structured packets. For example: ItemOptionOne/ItemOptionTwo

**Comment by Major-** [comment]
I too have looked into this, and as far as I can tell the unobfuscated opcodes are only present for the upstream (client -> server) frames, not the downstream ones. Have you found that this is not the case?

It's also worth mentioning that I plan on adding support for dynamic frame codec class generation (if you've seen saifix's project, like that) on start-up, which will heavily cut down on the boilerplate.

**Comment by Hadyn** [comment]
You are correct I believe. I haven't found evidence of unobfuscated downstream frames id's in the client as far as I'm aware. Those would have to be inputted as a parameter for encoding frames downstream.

Excellent! Less boilerplate the better. I feel like that'd be a massive move in the right direction to making this framework feel more cross compatible with other client builds.

**Comment by Major-** [comment]
Apollo isn't aiming to target 4xx+; scape-emu is a better fit for such revisions.

I plan on writing a server with a core that is actually revision independent at some point in the future, but it is unlikely to be based on apollo as apollo both explicitly and implicitly relies on a 3xx revision.

I'll leave this open for further discussion of runtime codec generation/a staged pipeline/etc.

**Comment by Hadyn** [comment]
Alright, when you're ready to revisit this let me know and we can brainstorm how this implementation would be drawn out.
