### ISSUE TITLE
Breaking the Chain

### ISSUE THREAD

**Issue by Hadyn** [apollo-rsps/apollo#63]
Apollo, as you may know, employs a handler chain for most content where a message is propagated downward until it meets its destination handler and the message is handled there. This design has a lot of benefits, like employing methods of validation to stop message propagation. However, in the scripting system it fragments logic between various scripts and even has issues with plugin dependency in situations where handler priority is not properly sorted. For this case I state the usage of items for quests versus other functions where a quest plugin may handle the logic for an item for a quest but in cases where other functionality needs to be deployed there have to be extraneous cases where conditions are placed to specifically state which handler has priority. Also the design does not appropriately manage future content implementations without having to take into account special considerations which reference to the cited example. The design also fails to keep logic centralized and in an essence of the fact of the idea, 'clean'. However I think the plugin system also fails this purpose, even if that purpose isn't intended I feel as if the plugin system fails in assisting the developer an easier way to develop content. Just an opinion though.

When speaking of propagating messages, the efficiency of finding the appropriate message handler for a specific message has as a worst case scenario is O(N). Theoretically when there are hundreds of handlers, or even a few thousand, is not efficient compared to O(1) when using a map collection structure.

For these reasons I think the handler chain should be converted to a one to one representation of a message to message dispatcher, and for each message dispatcher a one to one representation of handler conditions to a handler should be employed. Such in the case of the message dispatcher, similar methods could be deployed to all message sub-types. 

The proposal would be wide spread and I don't really expect it to be accepted right away however I feel the benefits outweigh the current implementation. A solution to this would include a logical centralized representation of all content, which the organization of such could be debated. Perhaps by category, or some other means.

**Comment by Major-** [comment]
>for each message dispatcher a one to one representation of handler conditions to a handler should be employed

Can you elaborate on this part specifically? What consists of a handler condition? Would it be e.g. the item or npc id, or more complicated than that?

**Comment by Hadyn** [comment]
A handler condition should be appropriately rephrased as message key, for example a numerical encoded identifier unique to the message which maps to a handler. For example for item on item you obviously encode the two item id's into a numerical key, the most significant word being the greater of the two item id's and the least significant word being the lesser of the two item id's. So yes, what you stated. Sorry for the lack of clarity I wrote this pretty early in the morning.

**Comment by Major-** [comment]
I like this idea a lot.

([Word](https://en.wikipedia.org/wiki/Word_%28computer_architecture%29) has an actual definition and is probably not what you are meaning here)

**Comment by Hadyn** [comment]
I meant it in the context of 16 bit integer. Which I thought was correct. The more you know. Do you want examples of how this would work?
