### ISSUE TITLE
Grouped region frame resets object state inappropriately

### ISSUE THREAD

**Issue by Major-** [apollo-rsps/apollo#64]
The grouped region update frame will sometimes reset an object to its default state when the player walks a reasonable distance away.

The object should not be reset.

**Comment by ryleykimmel** [comment]
Working on this -- will create a pull request when ready.

**Comment by WizardJesse1** [comment]
@ryleykimmel nice for keeping apollo fixed up :)

**Comment by Major-** [comment]
@ryleykimmel Seems like I've fixed it in the commit referenced above.

**Comment by ryleykimmel** [comment]
Looks good, what is meant by the TODO in Region#removeEntity?

**Comment by Major-** [comment]
Whoops @ryleykimmel , meant to remove that comment... will correct shortly.
