### ISSUE TITLE
Equipping Item's does not work 

### ISSUE THREAD

**Issue by WizardJesse1** [apollo-rsps/apollo#66]
I've tried several checks in the EquipItemHandler class and it seems like its not even sending it at all not sure if anyone else has had problems with this.

**Comment by WizardJesse1** [comment]
fixed the issue

**Comment by Major-** [comment]
What was the fix @WizardJesse1?

**Comment by WizardJesse1** [comment]
@Major- all I did was change the type in messages.xml for equiphandler

 <message>
    <type>org.apollo.game.message.impl.InventoryItemMessage</type>
    <chain>
      <handler>org.apollo.game.message.handler.EquipItemHandler</handler>
    </chain>
  </message>

**Comment by Major-** [comment]
@WizardJesse1 you definitely want to keep the verification handler in that chain - that's what prevents a load of item duplication bugs.

**Comment by WizardJesse1** [comment]
@Major- o yeah i forgot i removed it by accident since i though that was the problem sorry haha

**Comment by Major-** [comment]
@WizardJesse1 newest commit fixes this issue properly :-)
