### ISSUE TITLE
Plugin TypeError

### ISSUE THREAD

**Issue by LegendSky** [apollo-rsps/apollo#72]
Apollo with the latest update(Rubocop) gives an error on startup:

http://pastebin.com/7LtrFcvu

**Comment by ryleykimmel** [comment]
Interesting, I do not get this error when starting up the latest Apollo. Do you have any more context?

**Comment by LegendSky** [comment]
Sorry no I have no clue to be honest, I even cloned the latest Apollo to be sure it's not something I added.

**Comment by ryleykimmel** [comment]
It adds RuboCop (a Ruby code analyzer), which enforces code-style based upon your own configuration or by the community Ruby style guide.

**Comment by Major-** [comment]
@LegendSky what Jruby version are you using?

**Comment by ryleykimmel** [comment]
@LegendSky also what OS are you on, Java version, IDE?
