### ISSUE TITLE
Add ban/mute support

### ISSUE THREAD

**Issue by Major-** [apollo-rsps/apollo#76]
Add support for banning/muting users.

**Comment by Major-** [comment]
@lare96 @ryleykimmel would one of you be interested in this?

**Comment by Promises** [comment]
Should this be done via sql or?

**Comment by Major-** [comment]
@Promises apollo supports [several methods of serialization](https://github.com/apollo-rsps/apollo/tree/master/game/src/main/org/apollo/game/io/player), so it would depend on which one you are using. Right now the SQL one is non-existent, so it would only be added for the binary serializer.

Ban/mute status should be saved with the rest of the stuff for each player, not separately.

**Comment by lare96** [comment]
@Major- I wouldn't mind, would both of the flags be manipulated as attributes?

**Comment by Major-** [comment]
Yes, I think that's probably the way to go.

**Comment by Major-** [comment]
Added in c3ebfb4.
