### ISSUE TITLE
New players should be queued rather than added immediately.

### ISSUE THREAD

**Issue by Major-** [apollo-rsps/apollo#80]
When adding players to the World, they should be added to a queue which is processed every tick, rather than added immediately. This reduces the amount of locking required, and also prevents lots of new players from delaying the server pulse.

**Comment by lare96** [comment]
If you're not planning on doing this today I can submit a pull request for it

**Comment by Major-** [comment]
@ryleykimmel were you working on this?

**Comment by lare96** [comment]
Damn, I basically already finished it. Oh well, I'll just submit a pull request and you can see if it's done correctly.

**Comment by Major-** [comment]
@lare96 that would be great, thanks.

**Comment by lare96** [comment]
@Major- Should there be a login threshold? Or should all players in the queue be logged in

**Comment by Major-** [comment]
There should be a limit; the amount of players that can be logged out per pulse is [50](https://github.com/apollo-rsps/apollo/blob/master/game/src/main/org/apollo/game/service/GameService.java#L40), although that might be a little high for logging in. 20 seems like a reasonable limit, but I'm not opposed to it being set a bit higher than this if you think that's better.

**Comment by Major-** [comment]
Fixed in b3bc560.
