### ISSUE TITLE
GameObjects appear in inappropriate places

### ISSUE THREAD

**Issue by LegendSky** [apollo-rsps/apollo#82]
The latest version of Apollo has a bug with objects messing up, these are some pictures in Edgeville.
No errors are printed, and this was not the case 1-2 days ago. I suspect that the region updates could be faulty?

https://i.gyazo.com/6ab07f85f480c8575571189598110ffb.png
https://i.gyazo.com/fe9c80c6226c82a3edf3d1f4a0b059a2.png
https://i.gyazo.com/20cf4969922be76cfba7ae16a237698e.png
https://i.gyazo.com/40d3e38b3b55d36e54e6865cf4a11a0d.png

**Comment by Major-** [comment]
@LegendSky Thanks for the report, I think the commit referenced above fixes it. Please open another issue if you run into it again.
