### ISSUE TITLE
Appearance caching

### ISSUE THREAD

**Issue by Major-** [apollo-rsps/apollo#84]
The server should avoid sending the appearance block if the player has already seen the other player and the other player's appearance hasn't changed since that time.

**Comment by lare96** [comment]
Doesn't ScapeEmu have this?

**Comment by Major-** [comment]
Yes @lare96, for the most part it can probably be copy and pasted.

**Comment by davidi2** [comment]
relevant variable in scapeemu is the mob appearanceticket if anyone was looking

**Comment by ryleykimmel** [comment]
@Major- @garyttierney Close please, fixed in c7d1a5a
