### ISSUE TITLE
Odd error with MessageHandlerChainSet, not sure if because Eclipse

### ISSUE THREAD

**Issue by lare96** [apollo-rsps/apollo#89]
public <M extends Message> boolean notify(Player player, M message) {
		Deque<Class<? extends Message>> classes = this.classes.computeIfAbsent(message.getClass(),
				this::getMessageClasses);

		for (Class<? extends Message> type : classes) {
			MessageHandlerChain<? super M> chain = (MessageHandlerChain<? super M>) chains.get(type);

			if (chain != null && !chain.notify(player, message)) {
				return false;
			}
		}

		return true;
	}

This line in particular

		Deque<Class<? extends Message>> classes = this.classes.computeIfAbsent(message.getClass(),
				this::getMessageClasses);

What fixes it is

		Deque<Class<? extends Message>> classes = this.classes.computeIfAbsent(message.getClass(),
				it -> getMessageClasses(it));

Which doesn't make sense because they're exactly the same thing

**Comment by Major-** [comment]
What's the error?

**Comment by lare96** [comment]
[http://i.imgur.com/FWDNMXx.png]()

**Comment by Major-** [comment]
Yes, that's a bug in the eclipse compiler. Set it to use javac (or use IntelliJ instead).
