### ISSUE TITLE
Wilderness Level

### ISSUE THREAD

**Issue by WizardJesse1** [apollo-rsps/apollo#92]
When you enter it says you are in 0 wilderness level I don't know how to work github so I will just post here I guess the fix which is just missing + 1

# Determines the wilderness level for the specified player's position
def wilderness_level(player)
  (1 + (player.position.y - 3520) / 8).ceil
end

**Comment by lare96** [comment]
Why'd you close this? Was it added?

**Comment by Major-** [comment]
@WizardJesse1 what lare said

**Comment by WizardJesse1** [comment]
@Major- it wasn't added

**Comment by Major-** [comment]
@WizardJesse1 https://git-scm.com/doc

I think there's a varp to set which calculates this value, so this calculation might not be necessary anyway.
