### ISSUE TITLE
Other players cannot see your chat messages

### ISSUE THREAD

**Issue by lare96** [apollo-rsps/apollo#96]
Not sure if it's because of the client I'm using or something with updating but it seems as if other players can't see your chat messages. 

![](http://i.imgur.com/L7wXDV2.png)

**Comment by Frostbit3** [comment]
I believe that is to do with it being in tutorial island. There is code inside the client that prevents players from chatting in that area. Someone posted a tutorial on the forum about it.

**Comment by ryleykimmel** [comment]
Yes @Frostbit3 @lare96 go to a new area (off of Tutorial island) you cannot speak there.

**Comment by lare96** [comment]
Ahhhhhhh right right okay
