### ISSUE TITLE
MobRepositoryIterator logic flaw

### ISSUE THREAD

**Issue by ryleykimmel** [apollo-rsps/apollo#98]
next() doesn't work unless hasNext() is called first and remove() may be called whether or not next() was, also the iterator is lacking support for notifying when a concurrent modification exception has occurred.

**Comment by lare96** [comment]
/**
     * An {@link Iterator} implementation designed specifically
     * {@link MobileEntityList}s.
     * 
     * @author lare96 <http://github.org/lare96>
     * @param <E> The specific type of {@link MobileEntity} being managed within
     *        this {@code Iterator}.
     */
    private static final class MobileEntityListIterator<E extends MobileEntity> implements Iterator<E> {

        /**
         * The {@link MobileEntityList} this {@link Iterator} is dedicated to.
         */
        private final MobileEntityList<E> list;

        /**
         * If {@code null} values should be skipped.
         */
        private final boolean skipNull;

        /**
         * The current index.
         */
        private int curr;

        /**
         * The previous index.
         */
        private int prev = -1;

        /**
         * A factory method that returns a {@link MobileEntityListIterator} that
         * ignores {@code null} values completely. This is the default
         * implementation for all {@link MobileEntityList}s.
         * 
         * @param list The backing list.
         * @return The {@link Iterator} for the backing list.
         */
        public static <E extends MobileEntity> MobileEntityListIterator<E> excludeNull(MobileEntityList<E> list) {
            return new MobileEntityListIterator<E>(list, true);
        }

        /**
         * A factory method that returns a {@link MobileEntityListIterator} that
         * includes {@code null} values.
         * 
         * @param list The backing list.
         * @return The {@link Iterator} for the backing list.
         */
        public static <E extends MobileEntity> MobileEntityListIterator<E> includeNull(MobileEntityList<E> list) {
            return new MobileEntityListIterator<E>(list, false);
        }

        /**
         * Creates a new {@link MobileEntityListIterator}.
         *
         * @param list The {@link MobileEntityList} this {@link Iterator} is
         *        dedicated to.
         * @param skipNull If {@code null} values should be skipped.
         */
        private MobileEntityListIterator(MobileEntityList<E> list, boolean skipNull) {
            this.list = list;
            this.skipNull = skipNull;
        }

        @Override
        public boolean hasNext() {
            if (curr < list.capacity()) {
                if (skipNull) {
                    return skipNullIndexes();
                } else {
                    return true;
                }
            }
            return false;
        }

        @Override
        public E next() {
            if (skipNull) {
                skipNullIndexes();
            }
            checkPositionIndex(curr, list.capacity(), "No elements left");

            E mob = list.get(curr);
            prev = curr++;
            return mob;
        }

        @Override
        public void remove() {
            checkState(prev != -1, "remove() can only be called once after each call to next()");

            list.remove(list.get(prev));
            prev = -1;
        }

        /**
         * Forwards the {@code curr} marker until a {@code non-null} element is
         * found.
         * 
         * @return {@code true} if a non-null element is found, {@code false}
         *         otherwise.
         */
        private boolean skipNullIndexes() {
            while (list.get(curr) == null) {
                if (++curr >= list.capacity()) {
                    return false;
                }
            }
            return true;
        }
    }

is something I wrote and tested that satisfies all of the conditions except for notifications of concurrent modifications. speaking of which, is that even necessary to add?

**Comment by ryleykimmel** [comment]
Necessary, not really for this implementation (it is just how it is expected to work and how I wrote my unit tests) also it really should skip nulls by default, that shouldn't be an option,

**Comment by Major-** [comment]
Checking for concurrent modification is entirely optional.

**Comment by ryleykimmel** [comment]
Ping @garyttierney @Major- close this please, fixed in 637a18d
